# Generated by Django 4.2.16 on 2024-11-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_uploadeddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedData',
        ),
    ]
