# Generated by Django 4.2.16 on 2024-11-25 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0011_delete_uploadeddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_group', models.CharField(choices=[('LPG', 'LPG'), ('Naphtha', 'Naphtha'), ('Fueloil', 'Fueloil'), ('Gasoil', 'Gasoil'), ('Gasoline', 'Gasoline'), ('Bitumen', 'Bitumen'), ('Crude', 'Crude'), ('Others', 'Others')], max_length=50)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040)])),
                ('origin', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('tag1', models.CharField(blank=True, max_length=255, null=True)),
                ('tag2', models.CharField(blank=True, max_length=255, null=True)),
                ('tag3', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('upload_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
