# Generated by Django 4.2.16 on 2024-12-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_productentry_origin_alter_productentry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
